import type { SalesActivity, SalesLead } from "@/sales/types";

const createdAt = "2026-08-17T18:00:00.000Z";

export const seedSalesLeads: SalesLead[] = [
  {
    id: "finca-la-sevillana",
    prospectId: null,
    name: "Finca La Sevillana",
    city: "Écija",
    category: "Eventos",
    stage: "prototype",
    score: 78,
    estimatedValue: 550,
    contactName: null,
    phone: null,
    email: null,
    websiteUrl: null,
    socialUrl: null,
    prototypeUrl: null,
    repositoryFullName: "vornicx/fincalasevillana",
    owner: "antero",
    nextActionOwner: "antero",
    nextAction: "Llamar y presentar el prototipo",
    nextActionAt: "2026-08-18T08:30:00.000Z",
    lastContactAt: null,
    notes: "Prototipo preparado. La llamada debe centrarse en enseñar el resultado, no en vender una lista de funciones.",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "five-star-rentals",
    prospectId: null,
    name: "Five Star Rentals",
    city: "Marbella",
    category: "Luxury car rental",
    stage: "contacted",
    score: 86,
    estimatedValue: 700,
    contactName: null,
    phone: null,
    email: null,
    websiteUrl: "https://fivestars-rental.com/en/",
    socialUrl: null,
    prototypeUrl: "https://fivestarrentals.vercel.app",
    repositoryFullName: "vornicx/fivestarrentals",
    owner: "antero",
    nextActionOwner: "antero",
    nextAction: "Llamar si sigue sin responder al WhatsApp",
    nextActionAt: "2026-08-18T10:30:00.000Z",
    lastContactAt: "2026-08-15T18:00:00.000Z",
    notes: "El responsable pidió continuar por WhatsApp. Ya recibió el prototipo.",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "zusto-cafe",
    prospectId: null,
    name: "Zusto Café",
    city: "Puerto Banús",
    category: "Café",
    stage: "contacted",
    score: 82,
    estimatedValue: 650,
    contactName: "Encargada",
    phone: null,
    email: null,
    websiteUrl: null,
    socialUrl: null,
    prototypeUrl: null,
    repositoryFullName: null,
    owner: "antero",
    nextActionOwner: "antero",
    nextAction: "Segundo intento de llamada",
    nextActionAt: "2026-08-18T11:00:00.000Z",
    lastContactAt: "2026-08-17T17:00:00.000Z",
    notes: "La última llamada no fue contestada. Mantener el siguiente contacto corto y directo.",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "prisma-renting",
    prospectId: null,
    name: "PRISMA Renting",
    city: "España",
    category: "Renting",
    stage: "prototype",
    score: 88,
    estimatedValue: 700,
    contactName: null,
    phone: null,
    email: null,
    websiteUrl: "https://prismarenting.com/",
    socialUrl: null,
    prototypeUrl: "https://prismarenting.netlify.app/",
    repositoryFullName: null,
    owner: "vadim",
    nextActionOwner: "vadim",
    nextAction: "Terminar el prototipo y preparar el handoff comercial",
    nextActionAt: "2026-08-18T07:30:00.000Z",
    lastContactAt: null,
    notes: "Primero completar migración y elevar la landing. Después pasa a Antero para contacto.",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "cafe-los-rosarios",
    prospectId: null,
    name: "Café Los Rosarios",
    city: "Écija",
    category: "Café",
    stage: "researched",
    score: 74,
    estimatedValue: 500,
    contactName: null,
    phone: null,
    email: null,
    websiteUrl: null,
    socialUrl: null,
    prototypeUrl: null,
    repositoryFullName: null,
    owner: "vadim",
    nextActionOwner: "vadim",
    nextAction: "Preparar prototipo antes de contactar",
    nextActionAt: "2026-08-18T14:00:00.000Z",
    lastContactAt: null,
    notes: "Lead local para el modelo de web rápida de alta calidad.",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "la-bocana",
    prospectId: null,
    name: "La Bocana",
    city: "Puerto Banús",
    category: "Restaurante",
    stage: "contacted",
    score: 90,
    estimatedValue: 6500,
    contactName: null,
    phone: null,
    email: null,
    websiteUrl: null,
    socialUrl: null,
    prototypeUrl: null,
    repositoryFullName: null,
    owner: "antero",
    nextActionOwner: "antero",
    nextAction: "Revisar respuesta al correo y hacer follow-up",
    nextActionAt: "2026-08-19T09:00:00.000Z",
    lastContactAt: "2026-08-15T17:00:00.000Z",
    notes: "Oportunidad de mayor alcance. Mantener separada del paquete de webs rápidas.",
    createdAt,
    updatedAt: createdAt,
  },
];

export const seedSalesActivities: SalesActivity[] = [
  {
    id: "seed-five-star-whatsapp",
    leadId: "five-star-rentals",
    type: "message",
    outcome: null,
    note: "Prototipo enviado por WhatsApp tras la llamada inicial.",
    actor: "antero",
    createdAt: "2026-08-15T18:00:00.000Z",
  },
  {
    id: "seed-zusto-call",
    leadId: "zusto-cafe",
    type: "call",
    outcome: "no_answer",
    note: "No respondió la llamada.",
    actor: "antero",
    createdAt: "2026-08-17T17:00:00.000Z",
  },
];
