import { NextResponse } from "next/server";
import { z } from "zod";
import { isSensitiveAutofixPath, normalizeAutofixPath } from "@/autofix/policy";
import { authorizeAutofixTask, recordAutofixPullRequest } from "@/autofix/task";
import { ensureRepositoryPullRequest } from "@/lib/github-app";

export const runtime = "nodejs";
export const maxDuration = 30;

const bodySchema = z.object({
  leaseToken: z.string().min(32).max(256),
  gitRef: z.string().min(1).max(120),
  gitSha: z.string().regex(/^[a-f0-9]{40}$/i),
  summary: z.string().min(1).max(1_000),
  changedFiles: z.array(z.string().min(1).max(300)).min(1).max(4),
});

function findingTitle(payload: Record<string, unknown>): string {
  const finding = typeof payload.finding === "object" && payload.finding ? payload.finding as Record<string, unknown> : {};
  return String(finding.id ?? payload.summary ?? "quality finding").slice(0, 120);
}

export async function POST(request: Request, context: { params: Promise<{ id: string }> }) {
  const parsed = bodySchema.safeParse(await request.json().catch(() => null));
  if (!parsed.success) {
    return NextResponse.json({ error: "Invalid autofix publication request", issues: parsed.error.issues }, { status: 400 });
  }

  const { id } = await context.params;
  const task = await authorizeAutofixTask(id, parsed.data.leaseToken);
  if (!task) return NextResponse.json({ error: "Unauthorized or expired autofix task" }, { status: 401 });

  const expectedRef = `archic/autofix-${id.replaceAll("-", "").slice(0, 8)}`;
  if (parsed.data.gitRef !== expectedRef) {
    return NextResponse.json({ error: "Autofix branch does not match the scoped task" }, { status: 409 });
  }

  const changedFiles = Array.from(new Set(parsed.data.changedFiles.map(normalizeAutofixPath)))
    .filter((path): path is string => Boolean(path) && !isSensitiveAutofixPath(path as string));
  if (changedFiles.length !== parsed.data.changedFiles.length) {
    return NextResponse.json({ error: "Autofix publication contains an unsafe or duplicate path" }, { status: 400 });
  }

  const title = `fix: ${findingTitle(task.payload)}`.slice(0, 200);
  const body = [
    "## Archic Control autofix",
    "",
    `Task: \`${task.id}\``,
    `Project: \`${task.projectId}\``,
    `Finding: \`${task.findingId ?? "unlinked"}\``,
    `Commit: \`${parsed.data.gitSha}\``,
    "",
    parsed.data.summary,
    "",
    "### Changed files",
    ...changedFiles.map((path) => `- \`${path}\``),
    "",
    "### Safety boundary",
    "This draft PR was generated by Archic Control from one verified quality finding. The planner was limited to repository-provided file contents, blocked from secrets, CI, deployment configuration, dependencies and database files, and capped at four changed files.",
    "",
    "The finding remains in `fixing` until a later benchmark run independently verifies that the defect disappeared.",
  ].join("\n");

  try {
    const pull = await ensureRepositoryPullRequest(task.repositoryFullName, {
      head: parsed.data.gitRef,
      title,
      body,
    });
    await recordAutofixPullRequest(id, pull.url);
    return NextResponse.json({ ok: true, pullRequestUrl: pull.url, pullRequestNumber: pull.number });
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    return NextResponse.json({ error: message }, { status: 502 });
  }
}
